services:
  - type: web
    name: dr-assist-ai
    env: node
    plan: free
    region: singapore
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: HF_API_URL
        sync: false
      - key: CLIENT_URL
        value: https://dr-assist-fullstack.onrender.com
      - key: VITE_API_URL
        value: https://dr-assist-fullstack.onrender.com/api
      - key: PORT
        value: 10000
      - key: PYTHON_CMD
        value: python3
      - key: PYTHON_VERSION
        value: 3.10.0
